title: DEVSPOETICVS [SYSTEM_TERMINAL]
description: "[MODE] PORTFOLIO // TERMINAL | [CORE] JEKYLL // GITHUB PAGES | [ENGINE] ORDO AB CHAO"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .agent
  - .gemini
  - LICENSE
  - README.md